export const sheets = [
  "IAE",
  "ICM",
  "IEK",
  "IEL",
  "IEN",
  "IIN",
  "IMK",
  "ISP",
  "LCA",
  "LCI",
  "LCIk",
  "LEL",
  "LGH",
  "TSE",
];

export const initialColumn = "A";

export const initialRow = 11;

export enum ErrorCode {
  ERROR_FORM_DATA = "ERROR_FORM_DATA",
  ERROR_MISSING_FILE_KEY = "ERROR_MISSING_FILE_KEY",
  ERROR_MISSING_FILE = "ERROR_MISSING_FILE",
  ERROR_MISSING_EXCEL_FILE = "ERROR_MISSING_EXCEL_FILE",
  ERROR_MULTIPLE_FILES = "ERROR_MULTIPLE_FILES",
  ERROR_CONVERT_TO_BYTES = "ERROR_CONVERT_TO_BYTES",
  ERROR_CONVERT_TO_BUFFER = "ERROR_CONVERT_TO_BUFFER",
  ERROR_UPLOAD_PATH = "ERROR_UPLOAD_PATH",
  ERROR_FILE_PATH = "ERROR_FILE_PATH",
  ERROR_READ_UPLOADS_FOLDER = "ERROR_READ_UPLOADS_FOLDER",
  ERROR_DELETE_FILES = "ERROR_DELETE_FILES",
  ERROR_READ_EXCEL_FILE = "ERROR_READ_EXCEL_FILE",
  ERROR_READ_FILE = "ERROR_READ_FILE",
  ERROR_GET_HEADERS = "ERROR_GET_HEADERS",
  ERROR_EXTRACT_SUBJECTS = "ERROR_EXTRACT_SUBJECTS",
}
